INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (1,1,2,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (2,1,30,'Wajib Fakultas',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (3,1,28,'Wajib Rumpun',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (4,1,31,'Wajib Fakultas',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (5,1,10,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (6,1,4,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (7,1,1,'Wajib UI',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (8,1,33,'Wajib Fakultas',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (9,1,32,'Wajib Fakultas',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (10,1,44,'Wajib Prodi',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (11,1,3,'Wajib UI',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (12,1,29,'Wajib Rumpun',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (13,1,34,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (14,1,35,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (15,1,36,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (16,1,45,'Wajib Prodi',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (17,1,43,'Wajib Prodi',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (18,1,46,'Wajib Prodi',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (19,1,39,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (20,1,37,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (21,1,38,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (22,1,47,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (23,1,48,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (24,1,49,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (25,1,50,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (26,1,51,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (27,1,52,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (28,1,53,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (29,1,40,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (30,1,54,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (31,1,55,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (32,1,56,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (33,1,41,'Wajib Fakultas',7);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (34,1,57,'Wajib Prodi',7);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (35,1,42,'Wajib Fakultas',8);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (36,1,71,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (37,1,72,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (38,1,73,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (39,1,74,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (40,1,75,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (41,1,76,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (42,1,77,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (43,1,78,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (44,1,79,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (45,1,80,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (46,1,81,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (47,1,82,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (48,1,83,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (49,1,84,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (50,1,85,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (51,1,86,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (52,1,87,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (53,1,88,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (54,1,89,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (55,1,90,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (56,1,91,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (57,1,92,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (58,1,93,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (59,1,94,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (60,1,95,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (61,1,96,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (62,1,97,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (63,1,98,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (64,1,99,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (65,1,100,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (66,1,101,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (67,1,102,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (68,1,103,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (69,1,104,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (70,1,105,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (71,1,106,'Peminatan',0);