INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (1,1,2,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (2,1,30,'Wajib Fakultas',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (3,1,28,'Wajib Rumpun',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (4,1,31,'Wajib Fakultas',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (5,1,10,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (6,1,4,'Wajib UI',1);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (7,1,1,'Wajib UI',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (8,1,33,'Wajib Fakultas',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (9,1,32,'Wajib Fakultas',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (10,1,44,'Wajib Prodi',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (11,1,3,'Wajib UI',2);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (12,1,29,'Wajib Rumpun',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (13,1,34,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (14,1,35,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (15,1,36,'Wajib Fakultas',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (16,1,45,'Wajib Prodi',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (17,1,43,'Wajib Prodi',3);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (18,1,46,'Wajib Prodi',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (19,1,39,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (20,1,37,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (21,1,38,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (22,1,47,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (23,1,48,'Wajib Fakultas',4);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (24,1,49,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (25,1,50,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (26,1,51,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (27,1,52,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (28,1,53,'Wajib Prodi',5);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (29,1,40,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (30,1,54,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (31,1,55,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (32,1,56,'Wajib Prodi',6);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (33,1,41,'Wajib Fakultas',7);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (34,1,57,'Wajib Prodi',7);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (35,1,42,'Wajib Fakultas',8);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (36,1,71,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (37,1,72,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (38,1,73,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (39,1,74,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (40,1,75,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (41,1,76,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (42,1,77,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (43,1,78,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (44,1,79,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (45,1,80,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (46,1,81,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (47,1,82,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (48,1,83,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (49,1,84,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (50,1,85,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (51,1,86,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (52,1,87,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (53,1,88,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (54,1,89,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (55,1,90,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (56,1,91,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (57,1,92,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (58,1,93,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (59,1,94,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (60,1,95,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (61,1,96,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (62,1,97,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (63,1,98,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (64,1,99,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (65,1,100,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (66,1,101,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (67,1,102,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (68,1,103,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (69,1,104,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (70,1,105,'Peminatan',0);
INSERT INTO MATA_KULIAH_KURIKULUM(id,id_kurikulum,id_matkul,status_matkul,term) VALUES (71,1,106,'Peminatan',0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (72, 2, 2, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (73, 2, 30, 'Wajib Fakultas', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (74, 2, 29, 'Wajib Rumpun', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (75, 2, 31, 'Wajib Fakultas', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (76, 2, 10, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (77, 2, 4, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (78, 2, 1, 'Wajib UI', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (79, 2, 33, 'Wajib Fakultas', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (80, 2, 32, 'Wajib Fakultas', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (81, 2, 43, 'Wajib Prodi', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (82, 2, 3, 'Wajib UI', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (83, 2, 28, 'Wajib Rumpun', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (84, 2, 34, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (85, 2, 35, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (86, 2, 36, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (87, 2, 45, 'Wajib Prodi', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (88, 2, 44, 'Wajib Prodi', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (89, 2, 46, 'Wajib Prodi', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (90, 2, 39, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (91, 2, 37, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (92, 2, 38, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (93, 2, 47, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (94, 2, 48, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (95, 2, 49, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (96, 2, 50, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (97, 2, 51, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (98, 2, 52, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (99, 2, 53, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (100, 2, 40, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (101, 2, 54, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (102, 2, 55, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (103, 2, 56, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (104, 2, 41, 'Wajib Fakultas', 7);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (105, 2, 57, 'Wajib Prodi', 7);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (106, 2, 42, 'Wajib Fakultas', 8);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (107, 2, 71, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (108, 2, 72, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (109, 2, 73, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (110, 2, 74, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (111, 2, 75, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (112, 2, 76, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (113, 2, 77, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (114, 2, 78, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (115, 2, 79, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (116, 2, 80, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (117, 2, 81, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (118, 2, 82, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (119, 2, 83, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (120, 2, 84, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (121, 2, 85, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (122, 2, 86, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (123, 2, 87, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (124, 2, 88, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (125, 2, 89, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (126, 2, 90, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (127, 2, 91, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (128, 2, 92, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (129, 2, 93, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (130, 2, 94, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (131, 2, 95, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (132, 2, 96, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (133, 2, 97, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (134, 2, 98, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (135, 2, 99, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (136, 2, 100, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (137, 2, 101, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (138, 2, 102, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (139, 2, 103, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (140, 2, 104, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (141, 2, 105, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (142, 2, 106, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (143, 3, 1, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (144, 3, 30, 'Wajib Fakultas', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (145, 3, 29, 'Wajib Rumpun', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (146, 3, 31, 'Wajib Fakultas', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (147, 3, 12, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (148, 3, 3, 'Wajib UI', 1);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (149, 3, 2, 'Wajib UI', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (150, 3, 33, 'Wajib Fakultas', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (151, 3, 32, 'Wajib Fakultas', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (152, 3, 43, 'Wajib Prodi', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (153, 3, 4, 'Wajib UI', 2);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (154, 3, 28, 'Wajib Rumpun', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (155, 3, 34, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (156, 3, 35, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (157, 3, 36, 'Wajib Fakultas', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (158, 3, 45, 'Wajib Prodi', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (159, 3, 44, 'Wajib Prodi', 3);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (160, 3, 46, 'Wajib Prodi', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (161, 3, 39, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (162, 3, 37, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (163, 3, 38, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (164, 3, 47, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (165, 3, 48, 'Wajib Fakultas', 4);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (166, 3, 49, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (167, 3, 50, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (168, 3, 51, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (169, 3, 52, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (170, 3, 53, 'Wajib Prodi', 5);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (171, 3, 40, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (172, 3, 54, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (173, 3, 55, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (174, 3, 56, 'Wajib Prodi', 6);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (175, 3, 41, 'Wajib Fakultas', 7);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (176, 3, 57, 'Wajib Prodi', 7);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (177, 3, 42, 'Wajib Fakultas', 8);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (178, 3, 71, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (179, 3, 72, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (180, 3, 73, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (181, 3, 74, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (182, 3, 75, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (183, 3, 76, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (184, 3, 77, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (185, 3, 78, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (186, 3, 79, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (187, 3, 80, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (188, 3, 81, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (189, 3, 82, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (190, 3, 83, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (191, 3, 84, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (192, 3, 85, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (193, 3, 86, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (194, 3, 87, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (195, 3, 88, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (196, 3, 89, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (197, 3, 90, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (198, 3, 91, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (199, 3, 92, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (200, 3, 93, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (201, 3, 94, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (202, 3, 95, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (203, 3, 96, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (204, 3, 97, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (205, 3, 98, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (206, 3, 99, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (207, 3, 100, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (208, 3, 101, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (209, 3, 102, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (210, 3, 103, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (211, 3, 104, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (212, 3, 105, 'Peminatan', 0);
INSERT INTO mata_kuliah_kurikulum (id, id_kurikulum, id_matkul, status_matkul, term) VALUES (213, 3, 106, 'Peminatan', 0);
